SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS CATEGORY (
  Category_ID INT NOT NULL AUTO_INCREMENT,
  Category VARCHAR(255) NOT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Category_ID),
  UNIQUE KEY uq_category_name (Category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MODEL (
  Model_ID INT NOT NULL AUTO_INCREMENT,
  Model_Name VARCHAR(255) NOT NULL,
  Category_ID INT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Model_ID),
  UNIQUE KEY uq_model_name (Model_Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CUSTOMER (
  Customer_ID INT NOT NULL AUTO_INCREMENT,
  Customer_Ref_Number VARCHAR(255) NOT NULL,
  Customer_Name VARCHAR(255) NOT NULL,
  Branch VARCHAR(255) NOT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Customer_ID),
  KEY idx_customer_ref (Customer_Ref_Number),
  KEY idx_customer_name (Customer_Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RECIPIENTS (
  Recipients_ID INT NOT NULL AUTO_INCREMENT,
  Recipient_Name VARCHAR(255) NOT NULL,
  Department VARCHAR(255) DEFAULT NULL,
  `Position` VARCHAR(255) DEFAULT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Recipients_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROJECT (
  Project_ID INT NOT NULL AUTO_INCREMENT,
  Project_Ref_Number VARCHAR(255) NOT NULL,
  Project_Title VARCHAR(255) NOT NULL,
  Company_Full_Name VARCHAR(255) DEFAULT NULL,
  Warranty VARCHAR(255) DEFAULT NULL,
  Preventive_Maintenance VARCHAR(255) DEFAULT NULL,
  PM_Frequency INT DEFAULT 2,
  Start_Date DATE DEFAULT NULL,
  End_Date DATE DEFAULT NULL,
  Antivirus VARCHAR(255) DEFAULT NULL,
  file_path_logo VARCHAR(255) DEFAULT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Project_ID),
  UNIQUE KEY uq_project_ref (Project_Ref_Number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS INVENTORY (
  Inventory_ID INT NOT NULL AUTO_INCREMENT,
  Project_ID INT DEFAULT NULL,
  Customer_ID INT DEFAULT NULL,
  Asset_ID INT DEFAULT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Inventory_ID),
  UNIQUE KEY uq_inventory_asset (Asset_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ASSET (
  Asset_ID INT NOT NULL AUTO_INCREMENT,
  Asset_Serial_Number VARCHAR(255) DEFAULT NULL,
  Asset_Tag_ID VARCHAR(255) DEFAULT NULL,
  Item_Name VARCHAR(255) DEFAULT NULL,
  Recipients_ID INT DEFAULT NULL,
  Category_ID INT DEFAULT NULL,
  Model_ID INT DEFAULT NULL,
  Status VARCHAR(255) DEFAULT NULL,
  Windows VARCHAR(255) DEFAULT NULL,
  Microsoft_Office VARCHAR(255) DEFAULT NULL,
  Monthly_Prices DECIMAL(12,2) DEFAULT NULL,
  AV VARCHAR(255) DEFAULT NULL,
  Is_Flagged TINYINT(1) DEFAULT 0,
  Flag_Remarks TEXT DEFAULT NULL,
  Flag_Date DATETIME DEFAULT NULL,
  Flagged_By VARCHAR(255) DEFAULT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Asset_ID),
  UNIQUE KEY uq_asset_serial (Asset_Serial_Number),
  UNIQUE KEY uq_asset_tag (Asset_Tag_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ASSET_SOFTWARE_BRIDGE (
  Asset_ID INT NOT NULL,
  Software_ID INT NOT NULL,
  UNIQUE KEY uq_asset_software (Asset_ID, Software_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SOFTWARE (
  Software_ID INT NOT NULL AUTO_INCREMENT,
  Software_Name VARCHAR(255) NOT NULL,
  Price DECIMAL(12,2) DEFAULT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Software_ID),
  UNIQUE KEY uq_software_name (Software_Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PERIPHERAL_TYPE (
  Peripheral_Type_ID INT NOT NULL AUTO_INCREMENT,
  Peripheral_Type_Name VARCHAR(255) NOT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Peripheral_Type_ID),
  UNIQUE KEY uq_peripheral_type_name (Peripheral_Type_Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PERIPHERAL (
  Peripheral_ID INT NOT NULL AUTO_INCREMENT,
  Peripheral_Type_ID INT DEFAULT NULL,
  Asset_ID INT DEFAULT NULL,
  Serial_Code VARCHAR(255) DEFAULT NULL,
  `Condition` VARCHAR(255) DEFAULT NULL,
  Remarks TEXT DEFAULT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Peripheral_ID),
  KEY idx_peripheral_asset (Asset_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PMAINTENANCE (
  PM_ID INT NOT NULL AUTO_INCREMENT,
  Asset_ID INT DEFAULT NULL,
  PM_Date DATE DEFAULT NULL,
  Remarks TEXT DEFAULT NULL,
  Status VARCHAR(255) DEFAULT NULL,
  Created_By INT DEFAULT NULL,
  file_path_acknowledgement VARCHAR(255) DEFAULT NULL,
  signature_path VARCHAR(255) DEFAULT NULL,
  signed_at DATETIME DEFAULT NULL,
  BagiPihak VARCHAR(255) DEFAULT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (PM_ID),
  KEY idx_pm_asset (Asset_ID),
  KEY idx_pm_date (PM_Date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PM_CHECKLIST (
  Checklist_ID INT NOT NULL AUTO_INCREMENT,
  Category_ID INT DEFAULT NULL,
  Check_item_Long TEXT DEFAULT NULL,
  Display_Order INT DEFAULT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Checklist_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PM_RESULT (
  PM_Result_ID INT NOT NULL AUTO_INCREMENT,
  PM_ID INT DEFAULT NULL,
  Checklist_ID INT DEFAULT NULL,
  Is_OK_bool TINYINT(1) DEFAULT NULL,
  Remarks TEXT DEFAULT NULL,
  PRIMARY KEY (PM_Result_ID),
  KEY idx_pm_result_pm (PM_ID),
  KEY idx_pm_result_checklist (Checklist_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PM_SCHEDULE (
  Schedule_ID INT NOT NULL AUTO_INCREMENT,
  Project_ID INT NOT NULL,
  Scheduled_Date DATE NOT NULL,
  Is_Custom BOOLEAN DEFAULT TRUE,
  Notes TEXT DEFAULT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Schedule_ID),
  UNIQUE KEY unique_project_date (Project_ID, Scheduled_Date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HISTORY_LOG (
  Log_ID INT NOT NULL AUTO_INCREMENT,
  User_ID INT DEFAULT NULL,
  Table_Name VARCHAR(255) DEFAULT NULL,
  Record_ID VARCHAR(255) DEFAULT NULL,
  Action_Type VARCHAR(255) DEFAULT NULL,
  Action_Desc TEXT DEFAULT NULL,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Log_ID),
  KEY idx_history_user (User_ID),
  KEY idx_history_table (Table_Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HISTORY_LOG_CHANGES (
  Change_ID INT NOT NULL AUTO_INCREMENT,
  Log_ID INT DEFAULT NULL,
  Field_Name VARCHAR(255) DEFAULT NULL,
  Old_Value TEXT DEFAULT NULL,
  New_Value TEXT DEFAULT NULL,
  PRIMARY KEY (Change_ID),
  KEY idx_history_change_log (Log_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROJECT_SP_BRIDGE (
  Project_ID INT NOT NULL,
  SP_ID INT NOT NULL,
  `Support Type` VARCHAR(255) DEFAULT NULL,
  UNIQUE KEY uq_project_sp (Project_ID, SP_ID, `Support Type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MODEL_SPECS_BRIDGE (
  Model_ID INT NOT NULL,
  Attributes_ID INT NOT NULL,
  Attributes_Value TEXT DEFAULT NULL,
  UNIQUE KEY uq_model_spec (Model_ID, Attributes_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SPECS (
  Attributes_ID INT NOT NULL AUTO_INCREMENT,
  Attribute_Name VARCHAR(255) NOT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (Attributes_ID),
  UNIQUE KEY uq_attribute_name (Attribute_Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `users` (
  id INT NOT NULL AUTO_INCREMENT,
  full_name VARCHAR(255) DEFAULT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  password_hash VARCHAR(255) DEFAULT NULL,
  role VARCHAR(255) DEFAULT 'user',
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;