-- Minimal placeholder schema to satisfy app dependencies
CREATE TABLE IF NOT EXISTS `PROJECT` (
  `Project_ID` INT NOT NULL AUTO_INCREMENT,
  `Project_Name` VARCHAR(255) DEFAULT NULL,
  `Customer_ID` INT DEFAULT NULL,
  `Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Project_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ASSET` (
  `Asset_ID` INT NOT NULL AUTO_INCREMENT,
  `Asset_Tag` VARCHAR(255) DEFAULT NULL,
  `Model_ID` INT DEFAULT NULL,
  `Project_ID` INT DEFAULT NULL,
  `Serial_Number` VARCHAR(255) DEFAULT NULL,
  `Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Asset_ID`),
  KEY `idx_project` (`Project_ID`),
  CONSTRAINT `fk_asset_project` FOREIGN KEY (`Project_ID`) REFERENCES `PROJECT`(`Project_ID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `HISTORY_LOG` (
  `History_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT DEFAULT NULL,
  `Action` VARCHAR(255) DEFAULT NULL,
  `Details` TEXT,
  `Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`History_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `INVENTORY` (
  `Inventory_ID` INT NOT NULL AUTO_INCREMENT,
  `Asset_ID` INT DEFAULT NULL,
  `Quantity` INT DEFAULT 0,
  `Location` VARCHAR(255) DEFAULT NULL,
  `Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Inventory_ID`),
  KEY `idx_asset` (`Asset_ID`),
  CONSTRAINT `fk_inventory_asset` FOREIGN KEY (`Asset_ID`) REFERENCES `ASSET`(`Asset_ID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PM_SCHEDULE` (
  `Schedule_ID` INT NOT NULL AUTO_INCREMENT,
  `Project_ID` INT NOT NULL,
  `Scheduled_Date` DATE NOT NULL,
  `Is_Custom` BOOLEAN DEFAULT TRUE,
  `Notes` TEXT,
  `Created_At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Schedule_ID`),
  KEY `idx_pm_project` (`Project_ID`),
  CONSTRAINT `fk_pm_project` FOREIGN KEY (`Project_ID`) REFERENCES `PROJECT`(`Project_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- End of minimal schema
